_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 53
                - 55
            "2":
                - 1
                - 41
                - 53
                - 55
            "3":
                - 2
                - 3
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 4
dropout:
    value: 0
learning_rate:
    value: 1e-05
scheduler_patience:
    value: 10
weight_decay:
    value: 0
